@startuml
title Gateway flow
participant gateway
participant appserver
participant dataserver
gateway -> appserver: /test1
note right
url: v1/token/generate
header: api-key
param: card-no
end note

appserver -> dataserver: /test1
dataserver -> appserver: /test1
appserver -> gateway: /test1
@enduml
